version: '3.8'

services:

  minio:
    image: quay.io/minio/minio
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      INPUT_BUCKET_NAME: video-uploads
      OUTPUT_BUCKET_NAME: output
      BACKEND_URL: http://backend:5001
      MINIO_INTERFACE_EXTERNAL_URL: http://localhost:9001
    depends_on:
      - minio

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "5001:5001"
    environment:
      BACKEND_PORT: 5001
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      INPUT_BUCKET_NAME: video-uploads
      OUTPUT_BUCKET_NAME: output
    depends_on:
      - minio

